export default {
  index: 'Introduction',
  architecture: 'Architecture',
  'getting-started': 'Getting Started',
  '---security': {
    title: 'Security',
    type: 'separator',
  },
  'injection-filter': 'Injection Filter',
  'action-lock': 'Action Lock',
  'optimized-dom': 'Optimized DOM',
  'trust-warming': 'Trust Warming',
  'security-features': 'Advanced Security',
  '---optimization': {
    title: 'Token Optimization',
    type: 'separator',
  },
  'token-optimization': 'Overview',
  '---agents': {
    title: 'Agents & Automation',
    type: 'separator',
  },
  'agent-scripting': 'Agent Scripting DSL',
  'agent-communication': 'Agent-to-Agent Bus',
  'cost-tracking': 'Cost Tracking',
  '---tools': {
    title: 'Tools & Integration',
    type: 'separator',
  },
  'web-panel': 'Web Panel',
  tui: 'TUI Workbench',
  'mcp-tools': 'MCP Tools',
  'api-features': 'Vulpine API Features',
  'api-reference': 'Vulpine API Reference',
  'source-availability': 'Source Availability',
  'launch-checklist': 'Launch Checklist',
  foxbridge: 'Foxbridge CDP Proxy',
  '---deploy': {
    title: 'Deployment',
    type: 'separator',
  },
  docker: 'Docker (Vulpine-Box)',
  remote: 'Remote Access',
  '---guides': {
    title: 'Guides',
    type: 'separator',
  },
  'ai-browser-agent-security': 'AI Agent Security',
  'prevent-prompt-injection': 'Prevent Prompt Injection',
  'openclaw-camoufox-setup': 'OpenClaw + Camoufox Setup',
  'camoufox-vs-chrome': 'Camoufox vs Chrome',
  '---dev': {
    title: 'Development',
    type: 'separator',
  },
  building: 'Build from Source',
  contributing: 'Contributing',
}
